# Generated by Django 4.2.1 on 2023-06-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('items', models.TextField(verbose_name='items')),
                ('lat_long', models.CharField(max_length=100, verbose_name='lat_long')),
                ('full_details', models.TextField(verbose_name='full_details')),
            ],
        ),
    ]
